In [2]:
import sys
from dotenv import load_dotenv
import os
import requests
import pandas as pd
import json

In [3]:
load_dotenv()
load_dotenv('.env')
sports_data_api_key = os.getenv('SPORTS_DATA_API_KEY')

In [6]:
url = "https://api-nba-v1.p.rapidapi.com/players/statistics"
api_key_str = '?key='+sports_data_api_key

In [14]:

querystring = {"id":"2595","season":"2023"}

headers = {
	"X-RapidAPI-Key": "2033478d9cmsh61d5b3ff48db5abp1124d7jsndd48c0d84f61",
	"X-RapidAPI-Host": "api-nba-v1.p.rapidapi.com"
}

response = requests.get(url, headers=headers, params=querystring)
response_json = response.json()
#print(response.json())

stats_df = pd.json_normalize(response_json['response'])
stats_df = stats_df.drop(columns=['comment','team.logo','team.code','team.nickname','team.name','player.firstname','player.lastname'])
stats_df

,points,pos,min,fgm,fga,fgp,ftm,fta,ftp,tpm,...,totReb,assists,pFouls,steals,turnovers,blocks,plusMinus,player.id,team.id,game.id
0,15,PG,23,4,9,44.4,5,6,83.3,2,...,3,8,1,1,2,0,+14,2595,15,12520
1,14,PG,28,5,11,45.5,4,5,80.0,0,...,4,9,0,4,2,1,+13,2595,15,12541
2,20,PG,27,9,16,56.3,0,0,0,2,...,3,11,1,1,3,2,+6,2595,15,12552
3,21,PG,32,7,16,43.8,3,3,100.0,4,...,8,13,2,0,1,0,-1,2595,15,12579
4,19,PG,36,6,16,37.5,6,7,85.7,1,...,5,13,1,2,4,0,+2,2595,15,12590
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
75,24,PG,32,8,16,50.0,3,3,100.0,5,...,4,4,0,1,3,0,+13,2595,15,13962
76,16,PG,34,6,14,42.9,0,0,0,4,...,4,6,1,0,2,0,-14,2595,15,13967
77,17,PG,32,7,16,43.8,1,1,100.0,2,...,6,10,1,0,2,0,+12,2595,15,13973
78,6,PG,36,2,6,33.3,0,0,0,2,...,2,8,0,4,3,0,-12,2595,15,14003
79,34,PG,35,11,19,57.9,5,6,83.3,7,...,6,9,0,3,2,0,-17,2595,15,14004

In [15]:
stats_df.describe()

,points,fgm,fga,ftm,fta,tpm,tpa,offReb,defReb,totReb,assists,pFouls,steals,turnovers,blocks,player.id,team.id,game.id
count,80.000000,80.000000,80.000000,80.000000,80.000000,80.000000,80.000000,80.000000,80.000000,80.000000,80.000000,80.000000,80.000000,80.00000,80.000000,80.0,80.0,80.000000
mean,19.675000,7.087500,14.900000,2.700000,3.175000,2.800000,7.812500,0.575000,3.450000,4.025000,10.662500,1.050000,1.237500,2.33750,0.662500,2595.0,15.0,13249.162500
std,8.342017,2.951909,4.408278,2.313417,2.736416,1.983476,2.994061,0.924696,1.841161,2.238755,3.996656,1.029932,1.234973,1.50058,0.762138,0.0,0.0,437.450104
min,0.000000,0.000000,5.000000,0.000000,0.000000,0.000000,3.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.00000,0.000000,2595.0,15.0,12520.000000
25%,14.000000,5.000000,12.750000,1.000000,1.000000,1.000000,6.000000,0.000000,2.000000,2.000000,8.000000,0.000000,0.000000,1.00000,0.000000,2595.0,15.0,12872.750000
50%,19.000000,7.000000,15.000000,2.000000,3.000000,2.000000,7.000000,0.000000,3.000000,3.500000,11.000000,1.000000,1.000000,2.00000,1.000000,2595.0,15.0,13292.000000
75%,24.250000,9.000000,17.250000,4.000000,5.000000,4.000000,10.000000,1.000000,5.000000,6.000000,13.000000,2.000000,2.000000,3.00000,1.000000,2595.0,15.0,13593.750000
max,44.000000,15.000000,28.000000,8.000000,12.000000,9.000000,16.000000,5.000000,8.000000,10.000000,23.000000,5.000000,5.000000,7.00000,3.000000,2595.0,15.0,14004.000000