In [2]:
import sys
from dotenv import load_dotenv
import os
import requests
import pandas as pd
import json

In [3]:
load_dotenv()
load_dotenv('.env')
sports_data_api_key = os.getenv('SPORTS_DATA_API_KEY')

In [6]:
url = "https://api-nba-v1.p.rapidapi.com/players/statistics"

querystring = {"id":"978","season":"2023"}

headers = {
	"X-RapidAPI-Key": sports_data_api_key,
	"X-RapidAPI-Host": "api-nba-v1.p.rapidapi.com"
}

response_hartenstein = requests.get(url, headers=headers, params=querystring).json()
hartenstein_df = pd.json_normalize(response_hartenstein['response']).reset_index(drop=True)
hartenstein_df = hartenstein_df[['player.firstname','player.lastname','pos','points','min','fgm','fga','fgp','ftm','fta','tpm','tpa', 'tpp', 'offReb', 'defReb', 'totReb', 'assists', 'pFouls','steals', 'turnovers', 'blocks', 'plusMinus',]]
hartenstein_df

,player.firstname,player.lastname,pos,points,min,fgm,fga,fgp,ftm,fta,...,tpp,offReb,defReb,totReb,assists,pFouls,steals,turnovers,blocks,plusMinus
0,Isaiah,Hartenstein,C,9,20,3,5,60.0,3,4,...,0,0,3,3,3,2,0,4,1,+1
1,Isaiah,Hartenstein,C,7,16,3,5,60.0,0,0,...,100.0,1,3,4,1,1,1,2,0,-11
2,Isaiah,Hartenstein,C,9,18,4,8,50.0,1,2,...,0,4,1,5,2,2,1,1,0,-18
3,Isaiah,Hartenstein,C,13,23,6,11,54.5,0,0,...,33.3,4,4,8,2,3,1,2,0,-11
4,Isaiah,Hartenstein,C,7,26,3,4,75.0,1,2,...,0,5,3,8,2,5,0,1,0,-5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
85,Isaiah,Hartenstein,C,13,36,5,9,55.6,2,2,...,100.0,2,4,6,4,4,0,1,0,+9
86,Isaiah,Hartenstein,C,14,39,5,7,71.4,4,4,...,0,4,8,12,8,1,0,1,1,+21
87,Isaiah,Hartenstein,C,6,39,3,4,75.0,0,0,...,0,4,4,8,5,2,0,1,1,-2
88,Isaiah,Hartenstein,C,4,22,2,3,66.7,0,0,...,0,0,5,5,0,1,0,2,0,-28
89,Isaiah,Hartenstein,C,7,31,2,3,66.7,3,4,...,0,12,5,17,5,2,0,1,1,+17

In [7]:
url = "https://api-nba-v1.p.rapidapi.com/players/statistics"

querystring = {"id":"732","season":"2023"}

headers = {
	"X-RapidAPI-Key": sports_data_api_key,
	"X-RapidAPI-Host": "api-nba-v1.p.rapidapi.com"
}

response_Anunoby = requests.get(url, headers=headers, params=querystring).json()
Anunoby_df = pd.json_normalize(response_Anunoby['response']).reset_index(drop=True)
Anunoby_df = Anunoby_df[['player.firstname','player.lastname','pos','points','min','fgm','fga','fgp','ftm','fta','tpm','tpa', 'tpp', 'offReb', 'defReb', 'totReb', 'assists', 'pFouls','steals', 'turnovers', 'blocks', 'plusMinus',]]
Anunoby_df

,player.firstname,player.lastname,pos,points,min,fgm,fga,fgp,ftm,fta,...,tpp,offReb,defReb,totReb,assists,pFouls,steals,turnovers,blocks,plusMinus
0,O.G.,Anunoby,SF,14,20,6,7,85.7,0,0,...,100.0,0,0,0,3,0,2,0,0,+14
1,O.G.,Anunoby,SF,7,29,2,5,40.0,3,5,...,0,2,0,2,3,3,1,0,0,+9
2,O.G.,Anunoby,SF,15,23,6,10,60.0,1,1,...,40.0,1,3,4,4,2,1,3,1,+11
3,O.G.,Anunoby,SF,20,34,7,13,53.8,2,2,...,44.4,0,6,6,1,2,2,2,3,+6
4,O.G.,Anunoby,SF,11,28,5,8,62.5,0,1,...,25.0,0,3,3,0,2,2,1,0,+28
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
56,O.G.,Anunoby,SF,16,47,8,16,50.0,0,0,...,0,2,12,14,0,3,0,1,3,+3
57,O.G.,Anunoby,SF,17,50,7,12,58.3,1,2,...,40.0,1,5,6,0,3,2,4,1,-10
58,O.G.,Anunoby,SF,19,45,8,17,47.1,1,3,...,40.0,1,8,9,0,3,2,1,2,+8
59,O.G.,Anunoby,SF,13,42,5,14,35.7,0,0,...,42.9,0,9,9,4,1,2,2,0,+12
60,O.G.,Anunoby,SF,28,28,10,19,52.6,4,6,...,57.1,1,3,4,3,1,0,0,1,+10

In [9]:
url = "https://api-nba-v1.p.rapidapi.com/players/statistics"

querystring = {"id":"946","season":"2023"}

headers = {
	"X-RapidAPI-Key": sports_data_api_key,
	"X-RapidAPI-Host": "api-nba-v1.p.rapidapi.com"
}

response_Brunson = requests.get(url, headers=headers, params=querystring).json()
Brunson_df = pd.json_normalize(response_Brunson['response']).reset_index(drop=True)
Brunson_df = Brunson_df[['player.firstname','player.lastname','pos','points','min','fgm','fga','fgp','ftm','fta','tpm','tpa', 'tpp', 'offReb', 'defReb', 'totReb', 'assists', 'pFouls','steals', 'turnovers', 'blocks', 'plusMinus',]]
Brunson_df

,player.firstname,player.lastname,pos,points,min,fgm,fga,fgp,ftm,fta,...,tpp,offReb,defReb,totReb,assists,pFouls,steals,turnovers,blocks,plusMinus
0,Jalen,Brunson,PG,10,6,4,5,80.0,1,2,...,100.0,0,0,0,1,0,0,0,0,+7
1,Jalen,Brunson,PG,9,14,1,5,20.0,7,7,...,0,0,2,2,4,0,1,0,0,+15
2,Jalen,Brunson,PG,12,25,3,12,25.0,5,6,...,20.0,2,4,6,5,2,0,5,0,0
3,Jalen,Brunson,PG,15,33,6,21,28.6,0,1,...,37.5,1,2,3,6,3,3,2,0,-9
4,Jalen,Brunson,PG,31,33,11,21,52.4,1,2,...,66.7,0,3,3,5,1,0,1,0,+13
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
86,Jalen,Brunson,PG,43,44,14,26,53.8,14,14,...,25.0,1,5,6,6,2,0,4,1,+12
87,Jalen,Brunson,PG,29,32,11,18,61.1,4,6,...,50.0,0,2,2,5,2,3,2,0,+26
88,Jalen,Brunson,PG,26,38,10,26,38.5,4,7,...,33.3,0,0,0,6,2,1,5,0,-6
89,Jalen,Brunson,PG,18,31,6,17,35.3,6,9,...,0,2,1,3,5,1,2,2,0,-27
90,Jalen,Brunson,PG,44,43,18,35,51.4,6,7,...,33.3,0,4,4,7,2,0,3,0,+31

In [11]:
url = "https://api-nba-v1.p.rapidapi.com/players/statistics"

querystring = {"id":"2832","season":"2023"}

headers = {
	"X-RapidAPI-Key": sports_data_api_key,
	"X-RapidAPI-Host": "api-nba-v1.p.rapidapi.com"
}

response_McBride = requests.get(url, headers=headers, params=querystring).json()
McBride_df = pd.json_normalize(response_McBride['response']).reset_index(drop=True)
McBride_df = McBride_df[['player.firstname','player.lastname','pos','points','min','fgm','fga','fgp','ftm','fta','tpm','tpa', 'tpp', 'offReb', 'defReb', 'totReb', 'assists', 'pFouls','steals', 'turnovers', 'blocks', 'plusMinus',]]
McBride_df

,player.firstname,player.lastname,pos,points,min,fgm,fga,fgp,ftm,fta,...,tpp,offReb,defReb,totReb,assists,pFouls,steals,turnovers,blocks,plusMinus
0,Miles,McBride,PG,6,19,3,10,30.0,0,0,...,0,0,3,3,4,2,0,1,0,0
1,Miles,McBride,PG,16,11,6,6,100.0,0,0,...,100.0,0,1,1,2,1,1,2,0,-3
2,Miles,McBride,PG,5,23,2,7,28.6,0,2,...,25.0,0,0,0,5,0,1,0,0,-25
3,Miles,McBride,PG,16,33,6,18,33.3,2,2,...,25.0,1,1,2,6,3,4,3,0,-8
4,Miles,McBride,PG,2,5,1,3,33.3,0,0,...,0,0,1,1,1,0,1,0,0,+10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
78,Miles,McBride,PG,0,11,0,2,0,0,0,...,0,0,0,0,1,1,0,0,0,-13
79,Miles,McBride,PG,4,20,1,4,25.0,2,2,...,0,0,0,0,1,2,0,0,0,-22
80,Miles,McBride,PG,10,29,3,8,37.5,2,2,...,40.0,1,1,2,1,2,1,0,0,+11
81,Miles,McBride,PG,16,32,6,17,35.3,1,2,...,27.3,2,3,5,4,3,1,3,0,-16
82,Miles,McBride,PG,17,40,7,15,46.7,0,0,...,42.9,1,0,1,4,4,0,1,0,+26

In [13]:
url = "https://api-nba-v1.p.rapidapi.com/players/statistics"

querystring = {"id":"791","season":"2023"}

headers = {
	"X-RapidAPI-Key": sports_data_api_key,
	"X-RapidAPI-Host": "api-nba-v1.p.rapidapi.com"
}

response_hart = requests.get(url, headers=headers, params=querystring).json()
hart_df = pd.json_normalize(response_hart['response']).reset_index(drop=True)
hart_df = hart_df[['player.firstname','player.lastname','pos','points','min','fgm','fga','fgp','ftm','fta','tpm','tpa', 'tpp', 'offReb', 'defReb', 'totReb', 'assists', 'pFouls','steals', 'turnovers', 'blocks', 'plusMinus',]]
hart_df

,player.firstname,player.lastname,pos,points,min,fgm,fga,fgp,ftm,fta,...,tpp,offReb,defReb,totReb,assists,pFouls,steals,turnovers,blocks,plusMinus
0,Josh,Hart,SG,3,8,1,2,50.0,0,0,...,100.0,0,1,1,1,0,0,1,0,-9
1,Josh,Hart,SG,8,19,2,3,66.7,2,2,...,66.7,0,5,5,3,2,1,4,0,-16
2,Josh,Hart,SG,7,22,2,4,50.0,1,2,...,50.0,1,5,6,0,1,0,1,0,-1
3,Josh,Hart,SG,4,22,2,4,50.0,0,0,...,0,0,3,3,0,3,1,0,0,-2
4,Josh,Hart,SG,3,21,1,5,20.0,0,0,...,33.3,2,8,10,2,2,1,2,0,-10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
89,Josh,Hart,SG,24,48,9,13,69.2,5,8,...,100.0,4,9,13,8,3,3,5,1,+4
90,Josh,Hart,SG,19,48,8,12,66.7,2,2,...,33.3,2,13,15,7,3,1,5,1,+9
91,Josh,Hart,SG,10,43,4,7,57.1,1,2,...,100.0,0,18,18,4,5,2,4,0,-8
92,Josh,Hart,SG,2,24,1,6,16.7,0,0,...,0,0,3,3,2,1,0,2,0,-29
93,Josh,Hart,SG,18,39,7,16,43.8,2,2,...,28.6,2,9,11,3,2,1,3,1,+21

In [15]:
url = "https://api-nba-v1.p.rapidapi.com/players/statistics"

querystring = {"id":"962","season":"2023"}

headers = {
	"X-RapidAPI-Key": sports_data_api_key,
	"X-RapidAPI-Host": "api-nba-v1.p.rapidapi.com"
}

response_DiVincenzo = requests.get(url, headers=headers, params=querystring).json()
DiVincenzo_df = pd.json_normalize(response_DiVincenzo['response']).reset_index(drop=True)
DiVincenzo_df = DiVincenzo_df[['player.firstname','player.lastname','pos','points','min','fgm','fga','fgp','ftm','fta','tpm','tpa', 'tpp', 'offReb', 'defReb', 'totReb', 'assists', 'pFouls','steals', 'turnovers', 'blocks', 'plusMinus',]]
DiVincenzo_df

,player.firstname,player.lastname,pos,points,min,fgm,fga,fgp,ftm,fta,...,tpp,offReb,defReb,totReb,assists,pFouls,steals,turnovers,blocks,plusMinus
0,Donte,DiVincenzo,SG,8,23,2,8,25.0,2,2,...,40.0,0,3,3,2,2,0,1,0,-11
1,Donte,DiVincenzo,SG,4,20,2,3,66.7,0,0,...,0,0,3,3,3,2,2,1,0,-3
2,Donte,DiVincenzo,SG,7,24,3,7,42.9,0,0,...,33.3,0,2,2,0,2,0,2,0,-23
3,Donte,DiVincenzo,SG,15,25,3,12,25.0,6,6,...,30.0,0,3,3,3,3,1,6,0,-1
4,Donte,DiVincenzo,SG,0,15,0,4,0,0,0,...,0,0,3,3,2,1,0,0,0,+5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
91,Donte,DiVincenzo,SG,25,44,10,17,58.8,0,0,...,55.6,0,3,3,1,5,0,2,2,+10
92,Donte,DiVincenzo,SG,28,44,10,20,50.0,2,2,...,50.0,2,4,6,4,1,1,1,0,+15
93,Donte,DiVincenzo,SG,35,44,12,26,46.2,4,4,...,63.6,1,2,3,2,2,1,1,1,-10
94,Donte,DiVincenzo,SG,7,32,3,13,23.1,0,0,...,16.7,1,4,5,4,2,1,2,1,-40
95,Donte,DiVincenzo,SG,8,30,4,14,28.6,0,0,...,0,3,4,7,4,5,3,1,1,+16

In [16]:
url = "https://api-nba-v1.p.rapidapi.com/players/statistics"

querystring = {"id":"609","season":"2023"}

headers = {
	"X-RapidAPI-Key": sports_data_api_key,
	"X-RapidAPI-Host": "api-nba-v1.p.rapidapi.com"
}

response_Arcidiacono = requests.get(url, headers=headers, params=querystring).json()
Arcidiacono_df = pd.json_normalize(response_Arcidiacono['response']).reset_index(drop=True)
Arcidiacono_df = Arcidiacono_df[['player.firstname','player.lastname','pos','points','min','fgm','fga','fgp','ftm','fta','tpm','tpa', 'tpp', 'offReb', 'defReb', 'totReb', 'assists', 'pFouls','steals', 'turnovers', 'blocks', 'plusMinus',]]
Arcidiacono_df

,player.firstname,player.lastname,pos,points,min,fgm,fga,fgp,ftm,fta,...,tpp,offReb,defReb,totReb,assists,pFouls,steals,turnovers,blocks,plusMinus
0,Ryan,Arcidiacono,G,0,15,0,4,0,0,0,...,0,0,4,4,1,3,0,0,0,-5
1,Ryan,Arcidiacono,G,0,2,0,0,0,0,0,...,0,0,1,1,0,0,0,0,0,+1
2,Ryan,Arcidiacono,G,0,2,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,-2
3,Ryan,Arcidiacono,G,0,3,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,-4
4,Ryan,Arcidiacono,G,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,+1
5,Ryan,Arcidiacono,G,0,3,0,0,0,0,0,...,0,0,1,1,0,0,0,0,0,0
6,Ryan,Arcidiacono,G,0,2,0,0,0,0,0,...,0,0,1,1,1,0,1,0,0,-4
7,Ryan,Arcidiacono,G,0,1,0,0,0,0,0,...,0,0,1,1,1,0,0,0,0,-1
8,Ryan,Arcidiacono,G,0,3,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,+10
9,Ryan,Arcidiacono,G,0,2,0,1,0,0,0,...,0,0,1,1,1,0,0,0,0,-2
10,Ryan,Arcidiacono,G,0,1,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,-3
11,Ryan,Arcidiacono,G,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,+3
12,Ryan,Arcidiacono,G,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
13,Ryan,Arcidiacono,G,0,4,0,1,0,0,0,...,0,0,1,1,0,1,0,0,0,+2
14,Ryan,Arcidiacono,G,0,6,0,1,0,0,0,...,0,0,0,0,0,2,0,0,0,+1
15,Ryan,Arcidiacono,G,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,-5
16,Ryan,Arcidiacono,G,0,3,0,0,0,0,0,...,0,0,1,1,1,0,0,0,0,+3
17,Ryan,Arcidiacono,G,0,5,0,1,0,0,0,...,0,0,0,0,0,1,1,0,0,+3
18,Ryan,Arcidiacono,G,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,-4
19,Ryan,Arcidiacono,G,0,2,0,0,0,0,0,...,0,0,1,1,0,0,0,0,0,+3
20,Ryan,Arcidiacono,G,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0

In [18]:
url = "https://api-nba-v1.p.rapidapi.com/players/statistics"

querystring = {"id":"84","season":"2023"}

headers = {
	"X-RapidAPI-Key": sports_data_api_key,
	"X-RapidAPI-Host": "api-nba-v1.p.rapidapi.com"
}

response_burks = requests.get(url, headers=headers, params=querystring).json()
burks_df = pd.json_normalize(response_burks['response']).reset_index(drop=True)
burks_df = burks_df[['player.firstname','player.lastname','pos','points','min','fgm','fga','fgp','ftm','fta','tpm','tpa', 'tpp', 'offReb', 'defReb', 'totReb', 'assists', 'pFouls','steals', 'turnovers', 'blocks', 'plusMinus',]]
burks_df

,player.firstname,player.lastname,pos,points,min,fgm,fga,fgp,ftm,fta,...,tpp,offReb,defReb,totReb,assists,pFouls,steals,turnovers,blocks,plusMinus
0,Alec,Burks,SG,6,17,3,6,50.0,0,0,...,0,0,4,4,1,2,2,0,0,-12
1,Alec,Burks,SG,9,19,3,8,37.5,0,0,...,50.0,0,0,0,2,1,0,3,0,-12
2,Alec,Burks,SG,5,13,1,1,100.0,2,2,...,100.0,0,4,4,1,1,0,0,0,-8
3,Alec,Burks,SG,7,25,2,8,25.0,1,2,...,40.0,0,5,5,0,1,0,0,1,+9
4,Alec,Burks,SG,24,31,5,10,50.0,11,12,...,42.9,0,4,4,2,1,1,0,1,+28
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
68,Alec,Burks,SG,5,11,1,4,25.0,2,2,...,50.0,0,1,1,4,0,1,1,0,-3
69,Alec,Burks,SG,0,1,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
70,Alec,Burks,SG,14,21,4,6,66.7,4,5,...,50.0,0,4,4,1,2,1,0,1,-3
71,Alec,Burks,SG,20,23,5,11,45.5,8,10,...,33.3,2,3,5,2,2,0,0,0,-12
72,Alec,Burks,SG,18,23,6,11,54.5,1,2,...,62.5,0,5,5,0,1,0,0,0,+9

In [ ]:
#url = "https://api-nba-v1.p.rapidapi.com/players/statistics"
#
#querystring = {"id":"24","season":"2023"}
#
#headers = {
#	"X-RapidAPI-Key": sports_data_api_key,
#	"X-RapidAPI-Host": "api-nba-v1.p.rapidapi.com"
#}
#
#response_ = requests.get(url, headers=headers, params=querystring).json()
#_df = pd.json_normalize(response_['response']).reset_index(drop=True)
#_df = _df[['player.firstname','player.lastname','pos','points','min','fgm','fga','fgp','ftm','fta','tpm','tpa', 'tpp', 'offReb', 'defReb', 'totReb', 'assists', 'pFouls','steals', 'turnovers', 'blocks', 'plusMinus',]]
#_csv = _df.to_csv('../resources/knicks stats/.csv',index=False)

In [20]:
hartenstein_csv = hartenstein_df.to_csv('../resources/knicks stats/hartenstein.csv',index=False)
Anunoby_csv = Anunoby_df.to_csv('../resources/knicks stats/Anunoby.csv',index=False)
Brunson_csv = Brunson_df.to_csv('../resources/knicks stats/Brunson.csv',index=False)
McBride_csv = McBride_df.to_csv('../resources/knicks stats/McBride.csv',index=False)
hart_csv = hart_df.to_csv('../resources/knicks stats/hart.csv',index=False)
DiVincenzo_csv = DiVincenzo_df.to_csv('../resources/knicks stats/DiVincenzo.csv',index=False)
Arcidiacono_csv = Arcidiacono_df.to_csv('../resources/knicks stats/Arcidiacono.csv',index=False)
burks_csv = burks_df.to_csv('../resources/knicks stats/burks.csv',index=False)