In [2]:
import sys
from dotenv import load_dotenv
import os
import requests
import pandas as pd
import json

In [3]:
load_dotenv()
load_dotenv('.env')
sports_data_api_key = os.getenv('SPORTS_DATA_API_KEY')

In [4]:
url = "https://api-nba-v1.p.rapidapi.com/players/statistics"

querystring = {"id":"1897","season":"2023"}

headers = {
	"X-RapidAPI-Key": sports_data_api_key,
	"X-RapidAPI-Host": "api-nba-v1.p.rapidapi.com"
}

response_washington = requests.get(url, headers=headers, params=querystring).json()
washington_df = pd.json_normalize(response_washington['response']).reset_index(drop=True)
washington_df = washington_df[['player.firstname','player.lastname','pos','points','min','fgm','fga','fgp','ftm','fta','tpm','tpa', 'tpp', 'offReb', 'defReb', 'totReb', 'assists', 'pFouls','steals', 'turnovers', 'blocks', 'plusMinus',]]

In [6]:
querystring = {"id":"283","season":"2023"}

headers = {
	"X-RapidAPI-Key": sports_data_api_key,
	"X-RapidAPI-Host": "api-nba-v1.p.rapidapi.com"
}

response_jones = requests.get(url, headers=headers, params=querystring).json()
jones_df = pd.json_normalize(response_jones['response']).reset_index(drop=True)
jones_df = jones_df[['player.firstname','player.lastname','pos','points','min','fgm','fga','fgp','ftm','fta','tpm','tpa', 'tpp', 'offReb', 'defReb', 'totReb', 'assists', 'pFouls','steals', 'turnovers', 'blocks', 'plusMinus',]]
jones_df

,player.firstname,player.lastname,pos,points,min,fgm,fga,fgp,ftm,fta,...,tpp,offReb,defReb,totReb,assists,pFouls,steals,turnovers,blocks,plusMinus
0,Derrick,Jones Jr.,SF,3,10,1,3,33.3,1,1,...,0,0,1,1,0,0,1,0,1,-2
1,Derrick,Jones Jr.,SF,8,15,3,4,75.0,0,0,...,100.0,0,1,1,1,1,0,0,0,+14
2,Derrick,Jones Jr.,SF,1,12,0,3,0,1,2,...,0,0,1,1,0,0,0,1,0,-1
3,Derrick,Jones Jr.,SF,4,14,2,5,40.0,0,0,...,0,0,1,1,1,1,0,1,0,+1
4,Derrick,Jones Jr.,SF,22,27,7,10,70.0,4,6,...,66.7,0,4,4,0,0,0,1,0,+12
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
82,Derrick,Jones Jr.,SF,12,30,5,7,71.4,0,1,...,50.0,0,3,3,1,5,0,2,3,+20
83,Derrick,Jones Jr.,SF,6,36,3,5,60.0,0,0,...,0,2,3,5,2,3,0,1,1,+9
84,Derrick,Jones Jr.,SF,7,30,3,5,60.0,0,0,...,33.3,1,1,2,2,4,0,1,2,-15
85,Derrick,Jones Jr.,SF,9,28,3,12,25.0,2,2,...,20.0,3,2,5,2,4,0,1,0,-2
86,Derrick,Jones Jr.,SF,3,36,1,10,10.0,1,1,...,0,2,2,4,1,2,2,2,0,-14

In [7]:
querystring = {"id":"1859","season":"2023"}

headers = {
	"X-RapidAPI-Key": sports_data_api_key,
	"X-RapidAPI-Host": "api-nba-v1.p.rapidapi.com"
}

response_gafford = requests.get(url, headers=headers, params=querystring).json()
gafford_df = pd.json_normalize(response_gafford['response']).reset_index(drop=True)
gafford_df = gafford_df[['player.firstname','player.lastname','pos','points','min','fgm','fga','fgp','ftm','fta','tpm','tpa', 'tpp', 'offReb', 'defReb', 'totReb', 'assists', 'pFouls','steals', 'turnovers', 'blocks', 'plusMinus',]]
gafford_df

,player.firstname,player.lastname,pos,points,min,fgm,fga,fgp,ftm,fta,...,tpp,offReb,defReb,totReb,assists,pFouls,steals,turnovers,blocks,plusMinus
0,Daniel,Gafford,C,6,24,3,7,42.9,0,0,...,0,2,3,5,0,4,0,1,3,-6
1,Daniel,Gafford,C,5,18,2,5,40.0,1,2,...,0,1,2,3,1,2,1,0,1,+4
2,Daniel,Gafford,C,6,18,2,2,100.0,2,2,...,0,1,3,4,1,2,0,0,1,-9
3,Daniel,Gafford,C,6,21,2,2,100.0,2,4,...,0,1,4,5,0,5,0,0,2,-23
4,Daniel,Gafford,C,10,28,3,4,75.0,4,6,...,0,4,7,11,0,2,0,1,2,+8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
81,Daniel,Gafford,C,8,19,2,4,50.0,4,6,...,0,1,4,5,0,0,1,0,1,+8
82,Daniel,Gafford,C,13,22,5,8,62.5,3,3,...,0,4,2,6,0,3,0,1,0,+17
83,Daniel,Gafford,C,16,27,5,12,41.7,6,8,...,0,5,6,11,1,3,0,1,5,-2
84,Daniel,Gafford,C,13,27,4,6,66.7,5,9,...,0,2,5,7,2,2,1,3,1,-8
85,Daniel,Gafford,C,8,20,4,5,80.0,0,2,...,0,1,4,5,3,1,0,1,1,-8

In [8]:
querystring = {"id":"261","season":"2023"}

headers = {
	"X-RapidAPI-Key": sports_data_api_key,
	"X-RapidAPI-Host": "api-nba-v1.p.rapidapi.com"
}

response_irving = requests.get(url, headers=headers, params=querystring).json()
irving_df = pd.json_normalize(response_irving['response']).reset_index(drop=True)
irving_df = irving_df[['player.firstname','player.lastname','pos','points','min','fgm','fga','fgp','ftm','fta','tpm','tpa', 'tpp', 'offReb', 'defReb', 'totReb', 'assists', 'pFouls','steals', 'turnovers', 'blocks', 'plusMinus',]]
irving_df

,player.firstname,player.lastname,pos,points,min,fgm,fga,fgp,ftm,fta,...,tpp,offReb,defReb,totReb,assists,pFouls,steals,turnovers,blocks,plusMinus
0,Kyrie,Irving,PG,17,27,6,15,40.0,1,1,...,40.0,0,8,8,11,0,2,0,1,+12
1,Kyrie,Irving,PG,22,36,10,24,41.7,1,1,...,12.5,0,2,2,6,3,1,2,0,+1
2,Kyrie,Irving,PG,17,34,6,17,35.3,4,4,...,25.0,1,6,7,6,2,0,0,0,-7
3,Kyrie,Irving,PG,22,35,9,15,60.0,3,4,...,20.0,0,1,1,7,1,4,3,2,-12
4,Kyrie,Irving,PG,18,34,6,14,42.9,4,4,...,33.3,0,3,3,10,3,1,2,1,+8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
63,Kyrie,Irving,PG,14,35,6,14,42.9,1,1,...,14.3,1,3,4,6,4,2,0,0,+35
64,Kyrie,Irving,PG,30,42,11,19,57.9,3,5,...,55.6,1,5,6,4,3,2,1,2,+22
65,Kyrie,Irving,PG,20,37,7,14,50.0,3,3,...,75.0,0,1,1,3,2,2,4,1,-15
66,Kyrie,Irving,PG,9,41,2,8,25.0,5,6,...,0,2,1,3,11,4,2,2,2,+9
67,Kyrie,Irving,PG,22,41,10,17,58.8,0,0,...,33.3,2,3,5,7,2,1,4,1,+11

In [9]:
querystring = {"id":"963","season":"2023"}

headers = {
	"X-RapidAPI-Key": sports_data_api_key,
	"X-RapidAPI-Host": "api-nba-v1.p.rapidapi.com"
}

response_doncic = requests.get(url, headers=headers, params=querystring).json()
doncic_df = pd.json_normalize(response_doncic['response']).reset_index(drop=True)
doncic_df = doncic_df[['player.firstname','player.lastname','pos','points','min','fgm','fga','fgp','ftm','fta','tpm','tpa', 'tpp', 'offReb', 'defReb', 'totReb', 'assists', 'pFouls','steals', 'turnovers', 'blocks', 'plusMinus',]]
doncic_df

,player.firstname,player.lastname,pos,points,min,fgm,fga,fgp,ftm,fta,...,tpp,offReb,defReb,totReb,assists,pFouls,steals,turnovers,blocks,plusMinus
0,Luka,Doncic,PG,18,19,5,12,41.7,6,7,...,28.6,1,4,5,6,0,2,4,0,-1
1,Luka,Doncic,PG,33,34,13,25,52.0,4,7,...,27.3,1,12,13,10,1,2,4,0,+4
2,Luka,Doncic,PG,49,36,16,25,64.0,8,10,...,64.3,1,9,10,7,1,0,0,0,+9
3,Luka,Doncic,PG,35,40,11,22,50.0,7,10,...,50.0,0,12,12,12,4,1,6,1,+6
4,Luka,Doncic,PG,18,40,5,16,31.3,7,9,...,12.5,0,7,7,10,2,2,6,1,+11
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
75,Luka,Doncic,PG,35,39,14,26,53.8,5,5,...,25.0,1,6,7,10,4,1,2,0,+28
76,Luka,Doncic,PG,28,43,9,26,34.6,9,11,...,10.0,1,6,7,13,5,1,5,1,+9
77,Luka,Doncic,PG,19,41,6,19,31.6,6,10,...,12.5,0,6,6,9,0,2,5,0,-21
78,Luka,Doncic,PG,29,41,11,21,52.4,2,2,...,62.5,0,10,10,7,0,3,1,1,+6
79,Luka,Doncic,PG,22,40,7,17,41.2,7,10,...,25.0,3,12,15,5,1,2,4,0,+3

In [10]:
querystring = {"id":"215","season":"2023"}

headers = {
	"X-RapidAPI-Key": sports_data_api_key,
	"X-RapidAPI-Host": "api-nba-v1.p.rapidapi.com"
}

response_hardaway = requests.get(url, headers=headers, params=querystring).json()
hardaway_df = pd.json_normalize(response_hardaway['response']).reset_index(drop=True)
hardaway_df = hardaway_df[['player.firstname','player.lastname','pos','points','min','fgm','fga','fgp','ftm','fta','tpm','tpa', 'tpp', 'offReb', 'defReb', 'totReb', 'assists', 'pFouls','steals', 'turnovers', 'blocks', 'plusMinus',]]
hardaway_df

,player.firstname,player.lastname,pos,points,min,fgm,fga,fgp,ftm,fta,...,tpp,offReb,defReb,totReb,assists,pFouls,steals,turnovers,blocks,plusMinus
0,Tim,Hardaway Jr.,SF,8,18,3,8,37.5,0,0,...,33.3,0,1,1,0,0,1,1,0,0
1,Tim,Hardaway Jr.,SF,12,21,4,13,30.8,2,3,...,22.2,0,4,4,4,0,1,2,0,+7
2,Tim,Hardaway Jr.,SF,17,28,5,14,35.7,4,4,...,30.0,2,4,6,4,0,1,1,0,+9
3,Tim,Hardaway Jr.,SF,19,30,6,17,35.3,4,4,...,42.9,1,3,4,1,2,0,1,0,+13
4,Tim,Hardaway Jr.,SF,21,29,8,14,57.1,2,2,...,42.9,0,5,5,0,1,0,1,0,+6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
81,Tim,Hardaway Jr.,SF,6,16,2,5,40.0,1,2,...,50.0,0,3,3,0,1,0,0,0,-10
82,Tim,Hardaway Jr.,SF,0,6,0,1,0,0,0,...,0,0,1,1,1,0,1,0,0,+3
83,Tim,Hardaway Jr.,SF,2,17,1,5,20.0,0,0,...,0,0,2,2,0,0,0,0,0,-13
84,Tim,Hardaway Jr.,SF,17,19,6,10,60.0,3,4,...,50.0,0,2,2,1,1,0,0,0,+15
85,Tim,Hardaway Jr.,SF,8,16,3,9,33.3,0,0,...,40.0,0,2,2,1,0,1,0,0,-7

In [11]:
querystring = {"id":"4044","season":"2023"}

headers = {
	"X-RapidAPI-Key": sports_data_api_key,
	"X-RapidAPI-Host": "api-nba-v1.p.rapidapi.com"
}

response_lively = requests.get(url, headers=headers, params=querystring).json()
lively_df = pd.json_normalize(response_lively['response']).reset_index(drop=True)
lively_df = lively_df[['player.firstname','player.lastname','pos','points','min','fgm','fga','fgp','ftm','fta','tpm','tpa', 'tpp', 'offReb', 'defReb', 'totReb', 'assists', 'pFouls','steals', 'turnovers', 'blocks', 'plusMinus',]]
lively_df

,player.firstname,player.lastname,pos,points,min,fgm,fga,fgp,ftm,fta,...,tpp,offReb,defReb,totReb,assists,pFouls,steals,turnovers,blocks,plusMinus
0,Dereck II,Lively,C,2,23,1,2,50.0,0,0,...,0,2,2,4,0,3,1,3,3,-14
1,Dereck II,Lively,C,14,24,6,7,85.7,2,2,...,0,1,4,5,2,2,0,0,1,+9
2,Dereck II,Lively,C,16,31,7,8,87.5,2,3,...,0,5,5,10,1,4,1,1,1,+20
3,Dereck II,Lively,C,9,17,4,4,100.0,1,2,...,0,1,1,2,0,0,0,1,1,+1
4,Dereck II,Lively,C,2,14,1,2,50.0,0,0,...,0,1,5,6,0,5,0,0,1,-2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
61,Dereck II,Lively,C,12,25,5,5,100.0,2,2,...,0,2,5,7,1,4,0,2,1,+24
62,Dereck II,Lively,C,10,24,3,3,100.0,4,8,...,0,5,4,9,3,4,1,0,0,-2
63,Dereck II,Lively,C,2,13,1,3,33.3,0,0,...,0,3,1,4,1,3,0,2,0,-13
64,Dereck II,Lively,C,2,20,1,7,14.3,0,0,...,0,2,2,4,1,2,0,1,1,+18
65,Dereck II,Lively,C,12,27,2,7,28.6,8,12,...,0,3,5,8,1,3,0,1,0,+16

In [12]:
querystring = {"id":"2593","season":"2023"}

headers = {
	"X-RapidAPI-Key": sports_data_api_key,
	"X-RapidAPI-Host": "api-nba-v1.p.rapidapi.com"
}

response_green = requests.get(url, headers=headers, params=querystring).json()
green_df = pd.json_normalize(response_green['response']).reset_index(drop=True)
green_df = green_df[['player.firstname','player.lastname','pos','points','min','fgm','fga','fgp','ftm','fta','tpm','tpa', 'tpp', 'offReb', 'defReb', 'totReb', 'assists', 'pFouls','steals', 'turnovers', 'blocks', 'plusMinus',]]
green_df

,player.firstname,player.lastname,pos,points,min,fgm,fga,fgp,ftm,fta,...,tpp,offReb,defReb,totReb,assists,pFouls,steals,turnovers,blocks,plusMinus
0,Josh,Green,SG,6,22,2,6,33.3,0,1,...,66.7,1,2,3,0,1,1,2,0,+1
1,Josh,Green,SG,22,24,8,12,66.7,2,2,...,80.0,0,3,3,0,0,2,3,1,+18
2,Josh,Green,SG,11,30,3,5,60.0,3,4,...,100.0,2,0,2,1,4,1,0,0,+4
3,Josh,Green,SG,7,28,2,7,28.6,3,6,...,0,1,2,3,2,2,3,3,0,+8
4,Josh,Green,SG,12,34,5,10,50.0,0,0,...,50.0,1,1,2,3,0,1,1,0,+4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
63,Josh,Green,SG,4,18,1,3,33.3,1,1,...,33.3,0,2,2,0,0,1,0,0,+4
64,Josh,Green,SG,7,21,3,5,60.0,0,0,...,33.3,3,1,4,1,3,0,0,0,+7
65,Josh,Green,SG,11,25,4,9,44.4,0,0,...,37.5,1,3,4,3,3,0,1,0,-20
66,Josh,Green,SG,11,16,4,6,66.7,0,0,...,60.0,1,0,1,1,1,0,0,0,+9
67,Josh,Green,SG,3,15,1,3,33.3,0,0,...,33.3,1,0,1,1,3,1,1,0,+15

In [13]:
washington_csv = washington_df.to_csv('../resources/mavericks stats/washington.csv',index=False)
jones_csv = jones_df.to_csv('../resources/mavericks stats/jones.csv',index=False)
gafford_df.to_csv('../resources/mavericks stats/gafford.csv',index=False)
irving_df.to_csv('../resources/mavericks stats/irving.csv',index=False)
doncic_df.to_csv('../resources/mavericks stats/doncic.csv',index=False)
hardaway_df.to_csv('../resources/mavericks stats/hardaway.csv',index=False)
lively_df.to_csv('../resources/mavericks stats/lively.csv',index=False)
green_df.to_csv('../resources/mavericks stats/green.csv',index=False)