In [1]:
import sys
from dotenv import load_dotenv
import os
import requests
import pandas as pd
import json

In [2]:
load_dotenv()
load_dotenv('.env')
sports_data_api_key = os.getenv('SPORTS_DATA_API_KEY')

In [3]:
url = "https://api-nba-v1.p.rapidapi.com/players/statistics"

querystring = {"id":"972","season":"2023"}

headers = {
	"X-RapidAPI-Key": sports_data_api_key,
	"X-RapidAPI-Host": "api-nba-v1.p.rapidapi.com"
}

response_alexander = requests.get(url, headers=headers, params=querystring).json()
#print(json.dumps(response_alexander, indent=4))
alexander_df = pd.json_normalize(response_alexander['response']).reset_index(drop=True)
alexander_df = alexander_df[['player.firstname','player.lastname','pos','points','min','fgm','fga','fgp','ftm','fta','tpm','tpa', 'tpp', 'offReb', 'defReb', 'totReb', 'assists', 'pFouls','steals', 'turnovers', 'blocks', 'plusMinus',]]
alexander_df

,player.firstname,player.lastname,pos,points,min,fgm,fga,fgp,ftm,fta,...,tpp,offReb,defReb,totReb,assists,pFouls,steals,turnovers,blocks,plusMinus
0,Shai,Gilgeous-Alexander,PG,12,22,3,4,75.0,5,6,...,100.0,0,2,2,3,1,3,0,1,+13
1,Shai,Gilgeous-Alexander,PG,10,25,4,12,33.3,0,0,...,40.0,0,5,5,5,0,3,3,1,+11
2,Shai,Gilgeous-Alexander,PG,31,36,12,18,66.7,5,5,...,40.0,0,5,5,10,0,1,1,2,+19
3,Shai,Gilgeous-Alexander,PG,34,36,15,26,57.7,2,2,...,100.0,1,10,11,4,2,5,5,1,+4
4,Shai,Gilgeous-Alexander,PG,7,28,2,16,12.5,3,4,...,0,1,3,4,7,2,1,0,0,-22
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
79,Shai,Gilgeous-Alexander,PG,24,37,8,20,40.0,7,9,...,20.0,1,4,5,8,3,4,3,1,+22
80,Shai,Gilgeous-Alexander,PG,24,40,8,21,38.1,7,13,...,25.0,1,9,10,3,4,0,2,2,+7
81,Shai,Gilgeous-Alexander,PG,29,37,8,19,42.1,11,13,...,50.0,1,8,9,9,2,1,2,2,+21
82,Shai,Gilgeous-Alexander,PG,33,41,13,24,54.2,6,6,...,33.3,2,10,12,8,1,1,2,2,-6
83,Shai,Gilgeous-Alexander,PG,31,42,10,23,43.5,9,10,...,66.7,2,8,10,6,5,1,5,5,-9

In [4]:
url = "https://api-nba-v1.p.rapidapi.com/players/statistics"

querystring = {"id":"3448","season":"2023"}

headers = {
	"X-RapidAPI-Key": sports_data_api_key,
	"X-RapidAPI-Host": "api-nba-v1.p.rapidapi.com"
}

response_holmgren = requests.get(url, headers=headers, params=querystring).json()

holmgren_df = pd.json_normalize(response_holmgren['response']).reset_index(drop=True)
holmgren_df = holmgren_df[['player.firstname','player.lastname','pos','points','min','fgm','fga','fgp','ftm','fta','tpm','tpa', 'tpp', 'offReb', 'defReb', 'totReb', 'assists', 'pFouls','steals', 'turnovers', 'blocks', 'plusMinus',]]
holmgren_df

,player.firstname,player.lastname,pos,points,min,fgm,fga,fgp,ftm,fta,...,tpp,offReb,defReb,totReb,assists,pFouls,steals,turnovers,blocks,plusMinus
0,Chet,Holmgren,PF,21,16,7,10,70.0,5,7,...,100.0,2,7,9,1,1,0,0,1,0
1,Chet,Holmgren,PF,16,21,4,11,36.4,7,7,...,25.0,1,3,4,0,2,1,0,3,+4
2,Chet,Holmgren,PF,18,26,7,8,87.5,2,5,...,66.7,0,3,3,3,2,0,5,1,+7
3,Chet,Holmgren,PF,10,14,4,9,44.4,1,1,...,33.3,1,3,4,1,2,0,1,3,+7
4,Chet,Holmgren,PF,11,25,4,7,57.1,1,3,...,66.7,0,4,4,3,3,1,1,0,+14
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
88,Chet,Holmgren,PF,6,33,2,8,25.0,1,2,...,25.0,0,8,8,1,2,0,2,4,+11
89,Chet,Holmgren,PF,14,35,5,12,41.7,3,4,...,14.3,2,7,9,5,3,0,3,0,+10
90,Chet,Holmgren,PF,19,31,8,16,50.0,1,1,...,40.0,4,3,7,1,4,2,1,3,+18
91,Chet,Holmgren,PF,11,37,4,12,33.3,2,3,...,16.7,1,5,6,6,2,0,4,2,+4
92,Chet,Holmgren,PF,13,35,5,9,55.6,3,5,...,0,2,6,8,3,3,1,1,4,+1

In [7]:
url = "https://api-nba-v1.p.rapidapi.com/players/statistics"

querystring = {"id":"3505","season":"2023"}

headers = {
	"X-RapidAPI-Key": sports_data_api_key,
	"X-RapidAPI-Host": "api-nba-v1.p.rapidapi.com"
}

response_jaywilliams = requests.get(url, headers=headers, params=querystring).json()

jaywilliams_df = pd.json_normalize(response_jaywilliams['response']).reset_index(drop=True)
jaywilliams_df = jaywilliams_df[['player.firstname','player.lastname','pos','points','min','fgm','fga','fgp','ftm','fta','tpm','tpa', 'tpp', 'offReb', 'defReb', 'totReb', 'assists', 'pFouls','steals', 'turnovers', 'blocks', 'plusMinus',]]
jaywilliams_df

,player.firstname,player.lastname,pos,points,min,fgm,fga,fgp,ftm,fta,...,tpp,offReb,defReb,totReb,assists,pFouls,steals,turnovers,blocks,plusMinus
0,Jaylin,Williams,F,5,16,1,2,50.0,2,2,...,100.0,3,4,7,2,0,0,0,0,-1
1,Jaylin,Williams,F,18,23,7,10,70.0,2,3,...,50.0,4,5,9,3,1,0,1,1,-9
2,Jaylin,Williams,F,6,15,2,5,40.0,2,2,...,0,0,5,5,3,1,0,1,0,-2
3,Jaylin,Williams,F,6,13,2,5,40.0,2,2,...,0,0,2,2,2,3,1,0,1,+2
4,Jaylin,Williams,F,6,10,2,2,100.0,0,0,...,100.0,1,2,3,0,4,0,1,0,+1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
73,Jaylin,Williams,F,5,10,2,2,100.0,0,0,...,100.0,0,2,2,1,1,0,0,0,-2
74,Jaylin,Williams,F,3,11,1,1,100.0,0,0,...,100.0,0,2,2,0,1,1,2,2,-4
75,Jaylin,Williams,F,11,17,5,7,71.4,0,0,...,50.0,1,8,9,2,1,0,0,0,+3
76,Jaylin,Williams,F,8,14,3,6,50.0,0,0,...,50.0,0,4,4,2,1,0,1,0,-6
77,Jaylin,Williams,F,2,13,0,2,0,2,2,...,0,0,4,4,1,3,1,0,0,-5

In [8]:
url = "https://api-nba-v1.p.rapidapi.com/players/statistics"

querystring = {"id":"2808","season":"2023"}

headers = {
	"X-RapidAPI-Key": sports_data_api_key,
	"X-RapidAPI-Host": "api-nba-v1.p.rapidapi.com"
}

response_giddey = requests.get(url, headers=headers, params=querystring).json()

giddey_df = pd.json_normalize(response_giddey['response']).reset_index(drop=True)
giddey_df = giddey_df[['player.firstname','player.lastname','pos','points','min','fgm','fga','fgp','ftm','fta','tpm','tpa', 'tpp', 'offReb', 'defReb', 'totReb', 'assists', 'pFouls','steals', 'turnovers', 'blocks', 'plusMinus',]]
giddey_df

,player.firstname,player.lastname,pos,points,min,fgm,fga,fgp,ftm,fta,...,tpp,offReb,defReb,totReb,assists,pFouls,steals,turnovers,blocks,plusMinus
0,Josh,Giddey,SG,10,18,5,12,41.7,0,0,...,0,0,1,1,5,1,0,2,0,0
1,Josh,Giddey,SG,5,22,2,5,40.0,1,2,...,0,1,6,7,4,0,0,4,0,+16
2,Josh,Giddey,SG,19,24,9,12,75.0,1,1,...,0,0,7,7,5,0,0,2,0,+12
3,Josh,Giddey,SG,14,25,5,12,41.7,4,8,...,0,1,6,7,7,2,2,3,0,-12
4,Josh,Giddey,SG,16,32,7,14,50.0,0,0,...,66.7,1,5,6,6,1,0,3,0,+19
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
86,Josh,Giddey,SG,21,31,8,13,61.5,1,2,...,57.1,2,6,8,6,2,1,3,0,+15
87,Josh,Giddey,SG,14,29,5,10,50.0,0,0,...,66.7,0,3,3,1,2,0,1,1,+12
88,Josh,Giddey,SG,2,17,1,4,25.0,0,0,...,0,1,4,5,2,0,0,0,1,-7
89,Josh,Giddey,SG,8,11,3,6,50.0,2,2,...,0,0,2,2,0,0,0,1,0,-20
90,Josh,Giddey,SG,9,13,4,8,50.0,0,0,...,25.0,0,2,2,1,1,0,0,0,-1

In [9]:
url = "https://api-nba-v1.p.rapidapi.com/players/statistics"

querystring = {"id":"2040","season":"2023"}

headers = {
	"X-RapidAPI-Key": sports_data_api_key,
	"X-RapidAPI-Host": "api-nba-v1.p.rapidapi.com"
}

response_dort = requests.get(url, headers=headers, params=querystring).json()

dort_df = pd.json_normalize(response_dort['response']).reset_index(drop=True)
dort_df = dort_df[['player.firstname','player.lastname','pos','points','min','fgm','fga','fgp','ftm','fta','tpm','tpa', 'tpp', 'offReb', 'defReb', 'totReb', 'assists', 'pFouls','steals', 'turnovers', 'blocks', 'plusMinus',]]
dort_df

,player.firstname,player.lastname,pos,points,min,fgm,fga,fgp,ftm,fta,...,tpp,offReb,defReb,totReb,assists,pFouls,steals,turnovers,blocks,plusMinus
0,Luguentz,Dort,G,14,17,4,6,66.7,4,4,...,50.0,0,0,0,2,3,0,0,0,+5
1,Luguentz,Dort,G,24,24,8,12,66.7,3,4,...,55.6,0,4,4,0,0,0,0,0,+10
2,Luguentz,Dort,G,6,22,2,5,40.0,1,1,...,50.0,0,2,2,0,4,0,1,0,+1
3,Luguentz,Dort,G,5,24,2,8,25.0,1,2,...,0,2,3,5,1,3,1,2,0,-12
4,Luguentz,Dort,G,8,33,3,8,37.5,0,0,...,40.0,0,7,7,2,1,2,2,1,+13
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
85,Luguentz,Dort,G,12,39,4,9,44.4,0,0,...,50.0,2,2,4,3,4,0,1,0,+13
86,Luguentz,Dort,G,11,36,4,7,57.1,1,2,...,40.0,3,5,8,3,3,2,1,0,+3
87,Luguentz,Dort,G,7,26,2,9,22.2,1,2,...,40.0,4,0,4,1,5,2,3,0,+18
88,Luguentz,Dort,G,8,33,3,8,37.5,0,0,...,50.0,2,4,6,3,5,1,0,0,+1
89,Luguentz,Dort,G,8,40,3,9,33.3,0,0,...,28.6,1,1,2,2,6,2,2,1,-4

In [10]:
url = "https://api-nba-v1.p.rapidapi.com/players/statistics"

querystring = {"id":"3504","season":"2023"}

headers = {
	"X-RapidAPI-Key": sports_data_api_key,
	"X-RapidAPI-Host": "api-nba-v1.p.rapidapi.com"
}

response_jalwilliams = requests.get(url, headers=headers, params=querystring).json()

jalwilliams_df = pd.json_normalize(response_jalwilliams['response']).reset_index(drop=True)
jalwilliams_df = jalwilliams_df[['player.firstname','player.lastname','pos','points','min','fgm','fga','fgp','ftm','fta','tpm','tpa', 'tpp', 'offReb', 'defReb', 'totReb', 'assists', 'pFouls','steals', 'turnovers', 'blocks', 'plusMinus',]]
jalwilliams_df

,player.firstname,player.lastname,pos,points,min,fgm,fga,fgp,ftm,fta,...,tpp,offReb,defReb,totReb,assists,pFouls,steals,turnovers,blocks,plusMinus
0,Jalen,Williams,F,12,18,4,12,33.3,3,7,...,25.0,2,2,4,2,2,1,2,1,-10
1,Jalen,Williams,F,17,23,6,11,54.5,4,6,...,33.3,1,0,1,2,1,3,1,0,+18
2,Jalen,Williams,F,18,25,6,10,60.0,4,5,...,50.0,1,5,6,3,1,2,2,0,+15
3,Jalen,Williams,F,20,26,7,15,46.7,5,5,...,33.3,0,0,0,5,3,1,2,0,+3
4,Jalen,Williams,F,16,32,5,11,45.5,4,4,...,33.3,0,3,3,5,3,1,2,0,+8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
77,Jalen,Williams,F,21,35,9,16,56.3,0,0,...,75.0,1,8,9,5,1,2,3,0,+22
78,Jalen,Williams,F,24,38,9,17,52.9,4,5,...,33.3,1,7,8,4,2,2,3,1,+14
79,Jalen,Williams,F,18,36,6,15,40.0,4,6,...,40.0,2,3,5,5,1,0,1,1,+15
80,Jalen,Williams,F,20,39,7,17,41.2,4,4,...,50.0,1,3,4,4,4,1,1,1,+1
81,Jalen,Williams,F,16,38,7,12,58.3,1,2,...,50.0,0,6,6,8,2,0,3,1,-7

In [13]:
url = "https://api-nba-v1.p.rapidapi.com/players/statistics"

querystring = {"id":"2604","season":"2023"}

headers = {
	"X-RapidAPI-Key": sports_data_api_key,
	"X-RapidAPI-Host": "api-nba-v1.p.rapidapi.com"
}

response_joe = requests.get(url, headers=headers, params=querystring).json()

joe_df = pd.json_normalize(response_joe['response']).reset_index(drop=True)
joe_df = joe_df[['player.firstname','player.lastname','pos','points','min','fgm','fga','fgp','ftm','fta','tpm','tpa', 'tpp', 'offReb', 'defReb', 'totReb', 'assists', 'pFouls','steals', 'turnovers', 'blocks', 'plusMinus',]]
joe_df

,player.firstname,player.lastname,pos,points,min,fgm,fga,fgp,ftm,fta,...,tpp,offReb,defReb,totReb,assists,pFouls,steals,turnovers,blocks,plusMinus
0,Isaiah,Joe,SG,14,16,2,6,33.3,9,10,...,25.0,1,0,1,0,2,0,1,0,-7
1,Isaiah,Joe,SG,10,17,2,7,28.6,4,4,...,40.0,1,1,2,1,3,1,1,0,-6
2,Isaiah,Joe,SG,11,15,4,6,66.7,0,0,...,60.0,0,2,2,0,0,0,0,0,+15
3,Isaiah,Joe,SG,10,18,4,7,57.1,0,0,...,40.0,0,2,2,2,1,1,0,0,+11
4,Isaiah,Joe,SG,14,22,4,8,50.0,3,4,...,50.0,1,4,5,2,2,1,2,0,+14
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
84,Isaiah,Joe,SG,6,9,2,5,40.0,0,0,...,40.0,0,2,2,0,1,1,0,0,+15
85,Isaiah,Joe,SG,2,14,1,5,20.0,0,0,...,0,0,1,1,0,0,0,1,0,-4
86,Isaiah,Joe,SG,6,15,2,4,50.0,0,0,...,66.7,1,2,3,2,2,1,0,0,+12
87,Isaiah,Joe,SG,7,19,3,5,60.0,0,0,...,33.3,0,1,1,0,0,0,1,0,-9
88,Isaiah,Joe,SG,13,19,5,7,71.4,0,0,...,75.0,0,2,2,2,1,1,1,0,+2

In [14]:
url = "https://api-nba-v1.p.rapidapi.com/players/statistics"

querystring = {"id":"2863","season":"2023"}

headers = {
	"X-RapidAPI-Key": sports_data_api_key,
	"X-RapidAPI-Host": "api-nba-v1.p.rapidapi.com"
}

response_wiggins = requests.get(url, headers=headers, params=querystring).json()

wiggins_df = pd.json_normalize(response_wiggins['response']).reset_index(drop=True)
wiggins_df = wiggins_df[['player.firstname','player.lastname','pos','points','min','fgm','fga','fgp','ftm','fta','tpm','tpa', 'tpp', 'offReb', 'defReb', 'totReb', 'assists', 'pFouls','steals', 'turnovers', 'blocks', 'plusMinus',]]
wiggins_df

,player.firstname,player.lastname,pos,points,min,fgm,fga,fgp,ftm,fta,...,tpp,offReb,defReb,totReb,assists,pFouls,steals,turnovers,blocks,plusMinus
0,Aaron,Wiggins,SG,4,9,1,7,14.3,2,2,...,0,2,0,2,0,0,0,0,0,-4
1,Aaron,Wiggins,SG,16,29,6,12,50.0,2,4,...,50.0,2,2,4,2,4,0,0,0,-6
2,Aaron,Wiggins,SG,2,12,1,2,50.0,0,0,...,0,0,2,2,0,1,0,0,0,+8
3,Aaron,Wiggins,SG,4,16,2,3,66.7,0,0,...,0,1,5,6,0,3,1,0,0,0
4,Aaron,Wiggins,SG,2,11,1,3,33.3,0,0,...,0,1,2,3,0,2,0,1,0,-4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
84,Aaron,Wiggins,SG,6,16,3,5,60.0,0,0,...,0,2,1,3,1,0,1,4,0,-3
85,Aaron,Wiggins,SG,5,16,2,7,28.6,0,0,...,20.0,1,1,2,2,2,2,0,1,-2
86,Aaron,Wiggins,SG,16,23,5,7,71.4,3,4,...,75.0,0,5,5,2,1,1,2,1,+18
87,Aaron,Wiggins,SG,9,20,3,6,50.0,2,2,...,33.3,1,1,2,0,3,0,0,1,-1
88,Aaron,Wiggins,SG,6,22,3,7,42.9,0,0,...,0,0,4,4,0,0,1,1,0,+4

In [15]:
url = "https://api-nba-v1.p.rapidapi.com/players/statistics"

querystring = {"id":"4009","season":"2023"}

headers = {
	"X-RapidAPI-Key": sports_data_api_key,
	"X-RapidAPI-Host": "api-nba-v1.p.rapidapi.com"
}

response_wallace = requests.get(url, headers=headers, params=querystring).json()

wallace_df = pd.json_normalize(response_wallace['response']).reset_index(drop=True)
wallace_df = wallace_df[['player.firstname','player.lastname','pos','points','min','fgm','fga','fgp','ftm','fta','tpm','tpa', 'tpp', 'offReb', 'defReb', 'totReb', 'assists', 'pFouls','steals', 'turnovers', 'blocks', 'plusMinus',]]
wallace_df

,player.firstname,player.lastname,pos,points,min,fgm,fga,fgp,ftm,fta,...,tpp,offReb,defReb,totReb,assists,pFouls,steals,turnovers,blocks,plusMinus
0,Cason,Wallace,G,2,25,1,3,33.3,0,0,...,0,3,2,5,2,2,3,2,0,+19
1,Cason,Wallace,G,9,20,2,7,28.6,3,4,...,66.7,3,0,3,4,2,0,2,0,-9
2,Cason,Wallace,G,5,8,2,3,66.7,1,2,...,0,0,0,0,0,0,0,0,0,-4
3,Cason,Wallace,G,13,26,6,9,66.7,0,0,...,33.3,0,3,3,2,2,3,1,0,+1
4,Cason,Wallace,G,13,19,5,5,100.0,0,0,...,100.0,0,2,2,1,3,0,1,1,+9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
88,Cason,Wallace,G,5,18,2,4,50.0,0,0,...,50.0,1,1,2,1,0,3,0,0,+9
89,Cason,Wallace,G,0,14,0,2,0,0,0,...,0,0,0,0,0,1,2,1,0,+3
90,Cason,Wallace,G,7,23,2,5,40.0,1,2,...,50.0,1,2,3,3,1,1,0,0,+13
91,Cason,Wallace,G,6,22,3,5,60.0,0,0,...,0,1,2,3,1,1,2,0,0,-8
92,Cason,Wallace,G,3,14,1,3,33.3,0,0,...,33.3,1,0,1,0,1,0,0,0,0

In [18]:
alexander_df.to_csv('../Resources/thunder stats/alexander.csv', index=False)

In [19]:
alexander_df.to_csv('../resources/thunder stats/alexander.csv', index=False)
holmgren_df.to_csv('../resources/thunder stats/holmgren.csv', index=False)
jaywilliams_df.to_csv('../resources/thunder stats/jaywilliams.csv', index=False)
giddey_df.to_csv('../resources/thunder stats/giddey.csv', index=False)
dort_df.to_csv('../resources/thunder stats/dort.csv', index=False)
jalwilliams_df.to_csv('../resources/thunder stats/jalwilliams.csv', index=False)
joe_df.to_csv('../resources/thunder stats/joe.csv', index=False)
wiggins_df.to_csv('../resources/thunder stats/wiggins.csv', index=False)
wallace_df.to_csv('../resources/thunder stats/wallace.csv', index=False)